version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: "database"
    ports:
      - "5432:5432"
    env_file: 
      - var.env
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  api:
    build: .
    container_name: "rest_api"
    env_file:
      - var.env
    ports:
      - "8080:8080"
    depends_on: 
      - db
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge