services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: applicant
      POSTGRES_PASSWORD: temp123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
